server:
  port: 8080  # You can set this to whatever port you prefer

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: eureka-client                   # port:8081
          uri: lb://eureka-client-service     # Replace with your service name registered in Eureka
          predicates:
            - Path=/eureka-client/**          # Match requests with this path

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
