server:
  port: 8888  # Default port for Config Server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # URL of Eureka Server

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always  # Show detailed health information
  metrics:
    export:
      prometheus:
        enabled: true  # Enable the Prometheus metrics endpoint
    tags:
      application: config-server  # Add a global tag for all metrics
