management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, env
  endpoint:
    health:
      show-details: always  # Show detailed health information
  metrics:
    export:
      prometheus:
        enabled: true  # Enable the Prometheus metrics endpoint
    tags:
      application: config-server  # Add a global tag for all metrics