spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false  # Prevent it from fetching services from the registry, as it's only registering itself
    server:
      enable-self-preservation: false  # Disable self-preservation for the demo, optional for production
      eviction-interval-timer-in-ms: 60000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always  # Show detailed health information
  metrics:
    export:
      prometheus:
        enabled: true  # Enable the Prometheus metrics endpoint
    tags:
      application: eureka-server  # Add a global tag for all metrics