server:
  port: 8081

spring:
  application:
    name: eureka-client-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, env  # Expose health and info endpoints
  endpoint:
    env:
      enabled: true
    health:
      show-details: always  # Show detailed health information
