server:
  port: 8081

spring:
  application:
    name: eureka-client-service
  security:
    user:
      name: actuator-admin
      secret: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health, info, metrics, loggers, httptrace
  endpoint:
    env:
      enabled: true
    health:
      show-details: always  # Show detailed health information
